### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by cormag128** [cormag128/Python_Checkers#1]
Could use cleaning up, styling is poor right now, maybe build a checker class to hold the necessary information for certain functions to work

**Comment by TJenks13** [comment]
Added boundary checking, jump handling, and other input verification systems. No king system yet, but movements all nearly finished. Black moves need edited, due to need for AI system, right now just works with user input. Created classes for easy, medium, and hard modes with small explanations as to their purposes.
